language: go
sudo: required
services:
  - docker

#refer to https://github.com/pseudomuto/protoc-gen-doc/blob/master/.travis.yml
env:
  global:
    - PROTOC_RELEASE="https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip"
    - PROTOC_TARGET="${HOME}/protoc"
    - PATH="${PROTOC_TARGET}/bin:${PATH}"
    - secure: Tbet2rxD8QgjthAo+bxt41qbF2wUPTx0difGK5p4yQISK/njTuT5cqcxnOa4GIbyKtNtx0EgGnyVcQJiQkmZiF6Sabf0mtqU/CQ4PmVV76e9bHwA/CrTtudibMn16ozxuuxvhNxFOMQEhwcQOkW93M/Q9FZUEw9/CGpRGFfSzuA=

go:
  - 1.10.x
  - 1.11.x

before_install:
    - sudo apt-get install -y git build-essential openvswitch-switch
    - rm -rf /home/travis/gopath/.cache/govendor/github.com
    - go get -u github.com/kardianos/govendor
    - go get -u github.com/pierrre/gotestcover
    - govendor sync -v
    - if [ ! -d "${PROTOC_TARGET}" ]; then curl -fsSL "$PROTOC_RELEASE" > "${PROTOC_TARGET}.zip"; fi
    - if [ -f "${PROTOC_TARGET}.zip" ]; then unzip "${PROTOC_TARGET}.zip" -d "${PROTOC_TARGET}"; fi
    - go get -d -u github.com/golang/protobuf/protoc-gen-go
    - git -C "$(go env GOPATH)"/src/github.com/golang/protobuf checkout "v1.2.0"
    - go install github.com/golang/protobuf/protoc-gen-go
      # - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
    - make pb

script:
    - go vet ./...
    - sudo -E env PATH=$PATH TEST_OVS=1 TEST_VETH=1 TEST_DOCKER=1 gotestcover -parallelpackages=1 -coverprofile=coverage.txt -covermode=atomic `go list ./... | grep -v 'network-controller/messages'`

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: f4hCv7PeVjMrnLezDTQHgDUt100mx8KYG5kH9VbqPgdGqDibO8Gw979SCqHOZKpu9mCVblYV2brswy320JACj0v6KE5UrCHnpLEWpQcb4B5/AklmG1qo1dmpNdZ3Rlt12MzgHrFwSSapxhBS98K38hurXfM5q/14D0N1ddE9olwSxnNOFmg/wl8/D8JrVfxPIYMPt6MXN812U5XNy/cwinJ8xjBR/vsro76tqyLC/MYZ0O5knqUenBz6ZNxaQMcwSfW/7fNgfdXapccgIYXKVZZLPJh8T9+doh75ccYONNuI9dZsO7txQgarPV3SB/DRvw3DMUEh0RCaa/90zL9QXjiladLtU2F9eyCNCKiCL08atdPvNct0V75/C6KsVafJmZhWMJloIulAd26m7ytskQYhbBmLDFyjX2vdNEtXHOJm45BFQKQ3E9MvSIKzO7/l7gdmrRcgwOEHOsMMCrkQ4TSasMnjlGnZx13gRej0VHPzRYM0dNLyvnEPpBcgGo20pKmG/lIoORrzsrZDlHV1s7iSg/wp/R+H4c+otV17o5D57F3SIXICz7ZQ/gE6yP3CnBcBT/uHeL+rt5dYYBCo0iY0BgUVhUILQJbzLFm5GHokvbuAx2aaIf/RppMkVOPYUVmYAzbNb4qO7OsAyI9KFs+/T+lT2zNJZvuoK8Svokg=
